#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config top_padding			0
bspc config left_padding		0
bspc config bottom_padding		0
bspc config right_padding		0

bspc config border_width		1
bspc config window_gap			4

bspc config split_ratio			0.50
bspc config borderless_monocle	true
bspc config gapless_monocle		true

# change this to your desired app
kitty